In [20]:
import numpy as np
a=np.array([1,2,3])
b=np.array((4,5,6)) #tuple
print(a)
print(b)

[1 2 3]
[4 5 6]


In [21]:
b[1]=5
a[2]=6
print(a)
print(b)

[1 2 6]
[4 5 6]


In [22]:
import numpy as np
c=np.array([[0,1,2],[3,4,5]]) #see that there is extra []bracket
print(c) #c[0] and c[1] will give me the two arrays

[[0 1 2]
 [3 4 5]]


In [23]:
a[0] #this gives first element of a
a[0:3]

array([1, 2, 6])

In [28]:
#numpy array initialisation
#Zero Arrays
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
import numpy as np
np.arange(10,25,5) #Note the spelling of ARANGE. REMEMBER 10 SE START HUA 5 KE GAP SE BADHEGA, 25 KO EXCLUDE KARNA HAI

array([10, 15, 20])

In [34]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [36]:
import numpy as np
np.linspace(0,20,6) #Remember 0,20 both are included + total of 6 numbers are there

array([ 0.,  4.,  8., 12., 16., 20.])

In [37]:
import numpy as np
np.full((3,5),7)
#np.full((row,column),number to fill the whole space)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [41]:
import numpy as np
np.random.random((3,4))
#random is used to fill random numbers to 3X4 matrix

array([[0.07848232, 0.58800394, 0.415229  , 0.1966159 ],
       [0.84408247, 0.31275271, 0.30159624, 0.11826771],
       [0.55710979, 0.51214346, 0.53567855, 0.30394121]])

In [59]:
a=np.array([[2,3,4,5],[6,7,8,9]])
print(a.shape)#Shape is used to give the dimensions of the matrix. remember here i am using a variable 'a' to define my array.
print(a.ndim)# gives the number of dimensions of the array
print(a.dtype) #gives the datatype of array. Array has to be homogenous.

(2, 4)
2
int32


In [52]:
a.shape=(4,2)
print(a)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [53]:
print(a.shape[0])#number of Rows

4


In [54]:
print(a.shape[1])#number of Columns

2


In [56]:
a=np.arange(27)#Another form of arange, prints numbers from 0 to n-1
a.size #no. of elements

27

In [57]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [60]:
import numpy as np
a=np.arange(24,dtype=float)
print(a.size)
print(a.dtype)
b=a.reshape(3,4,2) #3 matrices of 4X2 dimensions.
print(b)


24
float64
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]]


In [61]:
np.sum([10,30])

40

In [63]:
np.sum([[0,1],[0,5]],axis=0) #corresponding elts ka sum or COLUMN WISE SUM

array([0, 6])

In [64]:
np.sum([[0,1],[5,6]],axis=1) #sum of elements within array or ROW WISE SUM

array([ 1, 11])

In [66]:
#various operations performed are:
#np.sum(a,b)
#np.subtract(a,b)
#np.divide(a,b)
#np.multiply(a,b)
#np.exp(a)
#np.sqrt(a)
#np.sin(a)
#np.cos(a)
#np.log(a)

In [73]:
a=[2,5]
b=[6,7]
print(np.sum(a))
print(np.sum([a,b]))
print(np.subtract(a,b))#this method does not work for sum?

7
20
[-4 -2]


In [74]:
print(np.divide(a,b)) #2/6 and 5/7

[0.33333333 0.71428571]


In [75]:
print(np.multiply(a,b))

[12 35]


In [76]:
print(np.cos(a)) #in radians

[-0.41614684  0.28366219]


In [77]:
import numpy as np
a=[1,2,4]
b=[2,4,4]
c=[3,2,5]
np.equal(a,b)

array([False, False,  True])

In [78]:
np.equal(b,c)

array([False, False, False])

In [79]:
print(np.array_equal(a,b)) #comparing array

False


In [80]:
#Aggregate Functions
a=[1,3,5]
print(np.sum(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a)) # correlation coefficient of an array
print(np.std(a)) #Standard Deviation of Array.

9
1
3.0
3.0
1.0
1.632993161855452


In [81]:
#Array Broadcasting
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])

print('First Array is: \n',a,'\n')
print('Second Array is: \n',b,'\n')
print('Sum of the two arrays is: \n',a+b, '\n')

First Array is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Second Array is: 
 [1 2 3] 

Sum of the two arrays is: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]] 



In [90]:
#Indexing and Slicing in Python
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[-1,0:2])
print(a[:,0:2])
print(a[:])#All Rows
print(a[:2])#0th row+ 1st row
print(a[1:])#1st and 2nd row
print(a[:,1:])#all rows+ 1st and 2nd row

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8]
[[1 2]
 [4 5]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [91]:
print(a[2:,:3]) #2nd row + 0,1,2 column

[[7 8 9]]


In [1]:
#Concatenating two arrays together
import numpy as np
a=[2,5,7]
b=[8,9,11]
np.concatenate((a,b),axis=0))

array([ 2,  5,  7,  8,  9, 11])

In [3]:
np.concatenate((a,b),axis=1)#Just ignore the answer and revise what is Axis=0,1

array([ 2,  5,  7,  8,  9, 11])

In [11]:
print(np.stack(a,b),axis=0)#Horizontal Stacking   #DOUBT
print(np.stack(a,b),axis=1)#Vertical Stacking

TypeError: only integer scalar arrays can be converted to a scalar index

In [4]:
np.vstack((a,b)) #Vertical Stacking

array([[ 2,  5,  7],
       [ 8,  9, 11]])

In [5]:
np.hstack((a,b)) #Horizontal Stacking

array([ 2,  5,  7,  8,  9, 11])

In [6]:
np.column_stack((a,b)) #Column wise Stacking!

array([[ 2,  8],
       [ 5,  9],
       [ 7, 11]])

In [10]:
a=np.array([[2,3,4],[5,6,7]])
b=np.array([[8,9,10],[11,12,13]])
print(np.concatenate((a,b),axis=0))#Row wise concatenation
print(np.concatenate((a,b),axis=1))#Column wise concatenation

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 2  3  4  8  9 10]
 [ 5  6  7 11 12 13]]


In [13]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("Matrix a is:")
print(a)
print("Matrix b is:")
print(b)
print("Horizontal Stacking:")
print(np.hstack((a,b)))
print("Vertical Stacking:")
print(np.vstack((a,b)))
print("Horizontal Concatenation:")
print(np.concatenate((a,b),axis=0))
print("Vertical Concatenation:")
print(np.concatenate((a,b),axis=1))
#Remember: Horizontal Stacking = Vertical Concatenation
#Remember: Vertical Stacking = Horizontal Concatenation
#Horizontal Stacking is adding two similar rows of diff matrices.
#Column Stack is same as Horizontal Stacking

Matrix a is:
[[1 2 3]
 [4 5 6]]
Matrix b is:
[[ 7  8  9]
 [10 11 12]]
Horizontal Stacking:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical Stacking:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Concatenation:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vertical Concatenation:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [16]:
#Splitting of Arrays
#np.split(array,index,axis) indices: int or list.
print(a)
print(np.split(a,2,0))
print(np.split(a,3,1))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [17]:
#Splitiing when index is changed to list
print(np.split(a,[1,2],axis=0)) #this is equal to a[:1] + a[1:2] + a[2:] 

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [18]:
print(np.split(a,[1,2],axis=1)) #this is equal to a[:,:1] + a[:, 1:2] + a[:, 2:]

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
